const imgMap ={
    'Alpine Credits':'/alpine-credits.png',
    'Alterna Savings':'/alterna-savings.png',
    'Atb Financial':'/atb-financial.png',
    'Banyan Mortgage':'/banyan-mortgage.png',
    'BMO':'/bmo.png',
    'Canada Life':'/canada-life-logo.svg',
    'Canadaland':'/canadalend.png',
    'Canadian Western Bank' :'/canadian-western-bank.png',
    'CIBC':'/cibc.svg',
    'Citadel Mortgages':'/citadel-mortgages.png',
    'Clover Mortgage':'/clover-mortgage.png',
    'CMLS':'/cmls.png',
    'Coast Capital':'/coast-capital.png',
    'Desjardins':'/desjardins.png',
    'DUCA':'/duca.png',
    'Equitable':'/equitable.svg',
    'First National':'/first-national.png',
    'FirstOntario':'/firstOntario.svg',
    'HSBC':'/hsbc.png',
    'ICICI':'/ICICI.png',
    'Investorsgroup':'/investorsgroup.png',
    'Lauretian':'/laurentian.svg',
    'Manulife':'/manulife.svg',
    'Marathon Mortgage':'/marathon-mortgage.jpg'

}